language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/stacktracey.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: fUvJIUUeZPXlSaCA9RZLfTOpQqTkOdXvR1wA5+eGEFmPk+3gcvCbjsiz1IWRTmhM4OBsc8wcx3p3aIAf5LvANcZ/KxJMEx4ltFdJiPoKIsSCY9vN4wIwIMBGXxdG8uLcmGPWr3Sn2hMX8Y4mRpey8N4A80chZE9Ambs35g+r2bDXWLKDbH7rQd+HVhmueweaQna1ttS2nUEc5WJJdHx/9CyJad85B3+UA1WVG6wWEQbSSy23VFNSFVLLvUboIeIOIraxPE8lJ1UmjZrxL/K2KRuykrKra8mvybY3+m8sNRZ8s4SIMSTm+ou5S3ClC2OOQtjfTH+kj8YemoNAsW+NOkkQxL4fTqo1g+7bXGaLegjFLhgIgEhsl1+mSqwcFj7lHmJCRxipNaCt8bhzKkI4z9+bk4zQYHXSEKwl5qwt1Itlz4RnlU8Tsu9GLSXC/4PPTvJlHhkor6kSExEoNXAMbrh/M97z57y+MpO0wy+Cj/4igjERerKeOGSkv32L3wJTsTl7igg7n/T6EDIqIy7zQVnQJy4Mzm+MfTTldk+Cn7MBeVqQWgjJLwNEZdgBITffccdHKgT/YyKfIm98rXWF6ngBs0qi8pyJ0iu9IrZnPY8+Rg2LXQEny32eUKTSTznC07he3arKYpCO5jVm4KNvDvwEP0hwhVyXFQZC0ccSvPA=
env:
  global:
  - secure: BaW4EsxqVZsPUzARGhwvnO2a7Ldl0BlVzEVLu8YBQcDNffN0tq5TtkOuTpKhOdVplckmoSXnncKcNBWfu392M9kM1riMRX8ssPiTy3j2duubHU+3yhSma5Ho6MOhB058h+RWMsLqGdw2yJazFt+egqMOtL7YhmMeYDdA7f1i0+lG9gZj/ViVM0pU0nIl3R8AhqRuTArUh5rVKAvI/5cFA8V1hePqR9bYbu0QU7w9eHWGhhtkIlsz6Fk5Jo+8176TtcLhKIjkmYr2ZrxYWhgILFYD0MqOR7v0L4WBebvDmcYHpVAeVMF29RzxVrnAkK03kZjh2cEejaqP/CZcd88PcmPM+kk7GcH/ftfqliMMQHjhHIEH+YBo5DP/jJX6ug1byyewvZOUtwRL9VUoiIHq87g1YnKZ2+t4bDkMJ6NaMlmy53uDjpY6JTjY1est7OAFdizfaQGal1Jr1rsklWS5fh0jI9zLvgGXc60pw7obBE8jlf1T189cvKS+BAflFv2Bu1kiWDErWocqn+0EMsWr6za+7mF9gRSl0O20oS2DUAFw2Xl1VDoVsWonJnItzLU8rtHCKRZvKMs4dI8eE8w97ScXJF0eld9dxjueJ/jfm59dY5hwBgHGp9xg+Jchoo8nhmir/Pn2MpGX7IxAM2RFj5LZh5+RvIbdQ+6wsXgiZ6M=
  - secure: GEV2Bg0mxEqP7RqZt0bFz0aR9VxvALxeajm74F44KZBxDzWCIQjXmasLyhIM4i5r2TyvRgVmB0OxRWd7Jbw4Ye9LgPbNx00NaW+p6I04uCyqGLKoB2NDqNRPgCoC71a92II8ZFLHNEgB9myNug18nXLmFxPcu/JY91nBgqYAiVIuGPSt5JnxYIPG2S7fkUov89MYJcnsc4cgBEqk70IzHn+yeSK8E6QSkshGhuYUMbS8kukYezXzQC47N2StQYvcPbBhNNlvGeWluoQ+7E06C6dkdhlv9SF5WYRZhGhoY4Krfaz19nT11MoTXZurBse0IjiW3J7uR9pPPfgWeK8PzwkUFxRg0FKmkoys4cGM11RbWmULpB181pFms1QXIVt+3zRrsg8sXj53yre+ExUDi2nzV01tcY2IIolOGAxRxM4Ipl5H++/WBuHdWXT4bmq52NQZrlohkIjP/7Pm+K2WxrsatG4V6CjWgLmhkc0A62ep0U4tnbCTFuVd2kFkg6t0CnQk74vLqI3ik/KayqusTSzGgJipTZWvGkKGvU++HUSXwqjBlvzFZGmMTYyEIGyyzo8r+furhHJT5YhERfBSJ+MM4K7HIzjm3RPqDPEABua53OwtNZC6Hq7kqpRabGt54W7zFRcfVkB1Ud5GI20LSUgOcH2k5dLd+V/zb7qi5EU=
