language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/stacktracey.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: XLa8p0J0PlbHye6703zr3jnaAueXr2MoBNKHGfd2DZZDbx9WA34wLAzDhMqonsdeHwQyn7j3NVhbrijfNS54w19bZeVw0MSK+DXT37Jsj4ZkiA7Q8lBQtIailzA7Yj1ugmpG3GZRpIDVgM/BaETWJ2FcQ1aaveU8J0hLTqtktpY23MpcamXIEZe5PA1UrzEihGrD/vamIw5s9shpT0zgHLkp+V5kftnJ77J0z34i6YP/PIaP9bbvlZU7kqw5dree6DDE5Elay13+768OJiI2bYfngcGriYmcydOG6xrzRLZPrtZhOjuQpcl/14hBI19MFU0f2xQVMejq3FGIOib8mowp8yUQEVURCfUP3fnxpop5Nn0vWFwcEJQzowKDpcNp9Gbv0+gSE8rn212SfQgkwHmoVQk6axLB8GU2tfYQxb/kqsNKbyOpEYQefhVfAnoWlpZlS7JkRs2Eij9BO6EQz+J1IMrO+hSo2utUfWrjkzlZElqXLMZ9k3BrZUkurWls3acsRLJEhTlgAmC4IpcAByzK4kCNaT3PKK/cByoF8hLXN2DyVVtIGF4nvgOJasQ1wLXd3w4rJ6kVSwnfg4nJd73mTC4EeW0IYw+4wZ/oFOkGgFoeaIyAdpRzyp3jIAS9IO0LX1c05diB9Drhy1uWz2MmaCmoBl4JqlUoHR2Zu58=
env:
  global:
  - secure: BaW4EsxqVZsPUzARGhwvnO2a7Ldl0BlVzEVLu8YBQcDNffN0tq5TtkOuTpKhOdVplckmoSXnncKcNBWfu392M9kM1riMRX8ssPiTy3j2duubHU+3yhSma5Ho6MOhB058h+RWMsLqGdw2yJazFt+egqMOtL7YhmMeYDdA7f1i0+lG9gZj/ViVM0pU0nIl3R8AhqRuTArUh5rVKAvI/5cFA8V1hePqR9bYbu0QU7w9eHWGhhtkIlsz6Fk5Jo+8176TtcLhKIjkmYr2ZrxYWhgILFYD0MqOR7v0L4WBebvDmcYHpVAeVMF29RzxVrnAkK03kZjh2cEejaqP/CZcd88PcmPM+kk7GcH/ftfqliMMQHjhHIEH+YBo5DP/jJX6ug1byyewvZOUtwRL9VUoiIHq87g1YnKZ2+t4bDkMJ6NaMlmy53uDjpY6JTjY1est7OAFdizfaQGal1Jr1rsklWS5fh0jI9zLvgGXc60pw7obBE8jlf1T189cvKS+BAflFv2Bu1kiWDErWocqn+0EMsWr6za+7mF9gRSl0O20oS2DUAFw2Xl1VDoVsWonJnItzLU8rtHCKRZvKMs4dI8eE8w97ScXJF0eld9dxjueJ/jfm59dY5hwBgHGp9xg+Jchoo8nhmir/Pn2MpGX7IxAM2RFj5LZh5+RvIbdQ+6wsXgiZ6M=
